# Generated by Django 6.0.1 on 2026-01-27 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='patient',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='scheduled_data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
