# Generated by Django 6.0.1 on 2026-01-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_patient_options_patient_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('confirmed', 'Waiting'), ('priority', 'Priority'), ('completed', 'Done'), ('canceled', 'Trash')], default=None, max_length=20, null=True),
        ),
    ]
