# Generated by Django 6.0.1 on 2026-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
